### ISSUE TITLE
Uncaught TypeError: InfiniteScroll is not a constructor

### ISSUE THREAD

**Issue by reilldesign** [three11/infinite-scroll#377]
After the update and the changes to the settings, I unfortunately only get an error message. Is there anything else I need to take into account or is the ReadMe not yet complete?

**Uncaught TypeError: InfiniteScroll is not a constructor**

`<script src="https://unpkg.com/@three11/infinite-scroll@2.0.0/dist/infinite-scroll.js"></script>

<script>
const infiniteScroll = new InfiniteScroll({
	element       : '.blog-items',
	next          : '[aria-label="Go to next page"]',
	item          : '.blog-item',
	disabledClass : 'disabled',
	hiddenClass   : 'hidden',
	responseType  : 'text/html',
	requestMethod: 'GET',
	viewportTriggerPoint: window.innerHeight / 2,
	debounceTime: 500,
	onComplete: function (container) {
		console.log(container)
	}
});
</script>`

**Comment by scriptex** [comment]
As i already told you, it is highly recommended to have a build step which bundles your files for you. The bundler of your choice should also automatically take care of the correct imports for you.

From what you pasted above I understand that you don't have Webpack/Rollup/Parcel/Vite or even Gulp/Grunt configured. It also looks like you're not using NPM or any other package manager (e.g. Bower). If that's correct, what you can do is continue using the script from `unpkg.com` but when initializing it you should change your code to:

```ts
const infiniteScroll = new InfiniteScroll.default({ 
  element: '.blog-items', 
  next: '[aria-label="Go to next page"]', 
  item: '.blog-item', 
  disabledClass: 'disabled', 
  hiddenClass: 'hidden', 
  responseType: 'text/html', 
  requestMethod: 'GET', 
  viewportTriggerPoint: window.innerHeight / 2, 
  debounceTime: 500, 
  onComplete: function (container) { 
    console.log(container) 
  } 
}); 
```
